# -*- coding: utf-8 -*-
"""DSB10_834R_API_PokeAPI.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Ra24OVA8PWJGMH_2nfaFneu9DlUU0iWc

# Fetch the pokemon data from PokeAPI
## Steps
- connect to PokeAPI
- find how many Mythical pokemon
- fetch into simple list
- save as csv


## Notices
From simple research, I found 23 mythical pokemons as of now (up to 9th Generation [Violet & Scarlet])\
From serebii.net, the national pokedex no. of these pokemons are:\
151, 251, 385, 386, 489,\
490, 491, 492, 493, 494,\
647, 648, 649, 719, 720,\
721, 801, 802, 807, 808,\
809, 893, and 1025.\
We can start from this list of no.
"""

from requests import get
from time import sleep

#create the list of the mythical pokemons no.
mythical_pokemons_no = [151, 251, 385, 386, 489, 490, 491, 492, 493, 494, 647, 648, 649, 719, 720, 721, 801, 802, 807, 808, 809, 893, 1025]

#assign start url
start_url = "https://pokeapi.co/api/v2/pokemon-form"

#create string for input types incase morethan 1 type
poketypes_string = ""

#create empty list for keeping pokemon data
pokemons_data = []

#create the loop to fecth the pokemon from api
for pokemon_no in mythical_pokemons_no:
  #get the data from API
  formresponse = get(start_url+"/"+str(pokemon_no))
  #convert form response to json
  pokemonmythform = formresponse.json()

  #save id and name
  pokeid = pokemonmythform['id']
  pokename = pokemonmythform['name']

  #save types (some pokemon have more than 1 type)
  for poketype in pokemonmythform['types']:
    poketypes_string += poketype['type']['name'] + " "

  #cutout extra space at the end of poketypes_string
  poketypes_string = poketypes_string[:-1]

  #save sprite url from the 'fron_default'
  sprites_url = pokemonmythform['sprites']['front_default']

  #save the data into list
  pokemon_data = [pokeid, pokename, poketypes_string, sprites_url]
  pokemons_data.append(pokemon_data)

  #reset the poketypes_string
  poketypes_string = ""

  #sleep for 2 second
  sleep(2)

pokemons_data

import csv
#create the csv file from pokemons_data
headers_data = ['id', 'name', 'types', 'sprites_url']

with open('mythical_pokemons.csv', 'w', encoding='UTF8', newline='') as f:
    writer = csv.writer(f)
    writer.writerow(headers_data)
    writer.writerows(pokemons_data)

!cat mythical_pokemons.csv